Repository TCDPaintYourself/paint-yourself-app, pull requests merged in 2022-02, with the labels that each got.

#1 basic nav implemented
  navigation/index.tsx
  package-lock.json
  screens/NewProjectScreen.tsx
  screens/ProfileScreen.tsx
  screens/SettingsScreen.tsx
Labels: enhancement

#2 Tsconfig and enable absolute imports
  App.tsx
  babel.config.js
  components/EditScreenInfo.tsx
  components/StyledText.tsx
  components/Themed.tsx
  components/__tests__/StyledText-test.js
  navigation/LinkingConfiguration.ts
  navigation/index.tsx
  screens/NewProjectScreen.tsx
  screens/NotFoundScreen.tsx
  screens/ProfileScreen.tsx
  screens/SettingsScreen.tsx
  tsconfig.json
Labels: enhancement

#3 Login register screen
  assets/images/auth_bgs/auth_background_1.jpg
  assets/images/auth_bgs/auth_background_2.jpg
  assets/images/auth_bgs/auth_background_3.jpg
  assets/images/auth_bgs/auth_background_4.jpg
  assets/images/auth_bgs/auth_background_5.jpg
  assets/images/auth_bgs/auth_background_6.jpg
  assets/images/auth_bgs/auth_background_7.jpg
  assets/images/auth_bgs/auth_background_8.jpg
  assets/images/auth_bgs/auth_background_default.jpg
  assets/images/logo_dark.png
  assets/images/logo_dark_sh.png
  assets/images/logo_light.png
  navigation/index.tsx
  screens/LoginRegisterScreen.tsx
  screens/ProfileScreen.tsx
  types.tsx
Labels: enhancement

#7 Add prettier as devdep, include test case
  .prettierignore
  .prettierrc
  App.tsx
  README.md
  app.json
  babel.config.js
  components/EditScreenInfo.tsx
  components/StyledText.tsx
  components/Themed.tsx
  components/__tests__/StyledText-test.js
  components/__tests__/__snapshots__/StyledText-test.js.snap
  constants/Layout.ts
  hooks/useCachedResources.ts
  hooks/useColorScheme.ts
  navigation/LinkingConfiguration.ts
  navigation/index.tsx
  package-lock.json
  package.json
  screens/LoginRegisterScreen.tsx
  screens/NotFoundScreen.tsx
  screens/ProfileScreen.tsx
  screens/SettingsScreen.tsx
  types.tsx
Labels: enhancement

#6 Create basic CI
  .github/workflows/ci.yml
Labels: enhancement

#9 Include workflow_dispatch for debugging
  .github/workflows/ci.yml
Labels: enhancement

#10 Remove ci-test from git pre-commit hook
  package.json
Labels: enhancement

#11 Add authentication
  App.tsx
  app.json
  babel.config.js
  components/Button/index.tsx
  components/ThemePicker/index.tsx
  constants/Firebase.ts
  hooks/useGoogleIdTokenAuthRequest.ts
  hooks/useUserContext.ts
  navigation/index.tsx
  package-lock.json
  package.json
  providers/UserProvider.tsx
  screens/LoginRegisterScreen.tsx
  screens/NewProjectScreen.tsx
  screens/ProfileScreen.tsx
  screens/SettingsScreen.tsx
  tsconfig.json
  types.tsx
  utils/firebase.ts
Labels: enhancement

#13 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#12 Profile screen
  assets/images/temp/cover_photo_temp.jpg
  assets/images/temp/google_profile_pic_temp.jpg
  navigation/index.tsx
  package.json
  screens/ProfileScreen.tsx
  types.tsx
Labels: enhancement

#8 Add Camera and Image Selector
  .prettierrc
  app.json
  components/Button/index.tsx
  components/Camera/index.tsx
  components/ThemePicker/index.tsx
  package-lock.json
  package.json
  screens/NewProjectScreen.tsx
  types.tsx
Labels: documentation, help wanted
