Repository TCDPaintYourself/paint-yourself-app, pull requests merged in 2022-03, with the labels that each got.

#16 Add api to vote/get theme votes (decorator not tested don't kill me)
  constants/ProjectThemes.ts
  package-lock.json
  package.json
  utils/theme_votes.ts
Labels: documentation, help wanted

#23 Upvote/downvote now return new vote count
  utils/themeVotes.ts
Labels: documentation

#22 Connect to API
  .prettierrc
  app.json
  assets/images/themes/caravaggio.jpg
  assets/images/themes/claude-monet.jpg
  assets/images/themes/da-vinci.jpg
  assets/images/themes/picasso.jpg
  assets/images/themes/rembrandt.jpg
  assets/images/themes/van-gogh.jpg
  assets/images/themes/whistler.jpg
  components/ThemePicker/index.tsx
  constants/ProjectThemes.ts
  navigation/index.tsx
  package-lock.json
  package.json
  patches/react-native-web+0.17.1.patch
  screens/ChooseStyleScreen.tsx
  screens/FinishedArtScreen.tsx
  screens/NewProjectScreen.tsx
  screens/ProfileScreen.tsx
  utils/convert.ts
  utils/themeVotes.ts
Labels: bug, enhancement
